globals:
  $: true
  require: true
  module: true
  parsley: true
rules:
  # Errors & best practices
  block-scoped-var: 1
  curly: [1, multi-line]
  default-case: 1
  eqeqeq: 2
  guard-for-in: 2
  linebreak-style: [2, windows]
  no-console: 1
  no-eval: 2
  no-multi-spaces: 2
  no-redeclare: 2
  no-unused-vars: 1
  no-use-before-define: 2
  quotes: [2, single]
  semi: [2, always]
  # Style
  brace-style: [2, 1tbs, { allowSingleLine: true }]
  camelcase: 1
  comma-spacing: [2, { before: false, after: true }]
  comma-style: [2, last]
  computed-property-spacing: [2, never]
  consistent-this: [1, _this]
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  new-cap: 2
  no-bitwise: 2
  no-mixed-spaces-and-tabs: 2
  no-nested-ternary: 2
env:
  browser: true
extends: eslint:recommended
